--[[
	Bagnon Config Localization Information: English Language
		This file must be present to have partial translations
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'frFR', true)

L.Columns = 'Colonnes'
L.Scale = 'Échelle'
L.Spacing = 'Espacement'
L.Opacity = 'Opacité'
L.FrameColor = 'Couleur de la fenêtre'
L.FrameBorderColor = 'Couleur bordure fenêtre'
L.Frame = 'Fenêtre'
L.Inventory = 'Inventaire'
L.Bank = 'Banque'
L.KeyRing = 'Trousseau'
L.GuildBank = 'Banque de guilde'
L.LockFramePositions = 'Verrouiller les positions des fenêtres'
L.ShowEmptyItemSlotBackground = 'Afficher un fond pour les emplacements d\'objets vides'
L.HighlightItemsByQuality = 'Mettre en évidence les objets par qualité'
L.HighlightQuestItems = 'Mettre en évidence les objets de quête'
L.ReverseSlotOrdering = 'Inverser l\'ordre des sacs'
L.ColorItemSlotsByBagType = 'Colorer les emplacements d\'objets vides par type de sac'
L.FrameLayer = 'Calque'
L.EnableBagFrame = 'Activer la fenêtre des sacs'
L.EnableMoneyFrame = 'Activer la fenêtre des pièces'
L.EnableDBOFrame = 'Activer la fenêtre DataBroker'
L.EnableSearchToggle = 'Activer le bouton de recherche'
L.EnableOptionsToggle = 'Activer bouton options'
L.EnableSortButton = 'Activer le bouton de tri'
L.EnableFrame_inventory = 'Activer la fenêtre d\'inventaire'
L.EnableFrame_bank = 'Activer la fenêtre de banque'
L.EnableFrame_keys = 'Activer le trousseau'
L.SettingRequiresRestart = 'Ce paramètre prendra effet lors de votre prochaine connexion'
L.EnableAutoDisplay_bank = 'Afficher l\'inventaire lors de la visite à la banque'
L.EnableAutoDisplay_ah = 'Afficher l\'inventaire lors de la visite à l\'hôtel des ventes'
L.EnableAutoDisplay_vendor = 'Afficher l\'inventaire lors de la visite chez un vendeur'
L.EnableAutoDisplay_trade = 'Afficher l\'inventaire lors de l\'échange d\'objets'
L.EnableAutoDisplay_craft = 'Afficher l\'inventaire lors de l\'artisanat'
L.EnableAutoDisplay_mail = 'Afficher l\'inventaire lors de la consultation d\'une boîte aux lettres'
L.EnableAutoDisplay_guildbank = 'Afficher l\'inventaire lors de la visite à la banque de guilde'
L.EnableAutoDisplay_player = 'Afficher l\'inventaire avec la fenêtre personnage'
L.DisplaySettings = 'Affichage automatique'
L.DisplaySettingsTitle = 'Paramètres d\'affichage automatique des fenêtres'
L.FrameSettings = 'Paramètres des fenêtres'
L.FrameSettingsTitle = 'Paramètres spécifiques à une fenêtre de Bagnon'
L.GeneralSettings = 'Paramètres généraux'
L.GeneralSettingsTitle = 'Paramètres de configuration généraux pour Bagnon'
L.EnableBlizzardBagPassThrough = 'Afficher les fenêtres Blizzard pour les sacs désactivés'
L.EnableBagBreak = 'Activer la rupture des sacs'
L.ColorSettings = 'Paramètres de couleur'
L.ColorSettingsTitle = 'Paramètres de coloration des emplacements d\'objets'
L.ItemHighlightOpacity = 'Luminosité de mise en évidence des objets'
L.ItemSlotColor_ammo = 'Couleur des emplacements de sac de munitions'
L.ItemSlotColor_trade = 'Couleur des emplacements de sac de commerce'
L.ItemSlotColor_shard = 'Couleur des emplacements de sac d\'âmes'
L.ItemSlotColor_keyring = 'Couleur des emplacements du trousseau'
